# 适用于讯飞星火的spark-lite 参考 https://www.xfyun.cn/doc/spark/Web.html#_2-function-call%E8%AF%B4%E6%98%8E

llm:
  api_type: "spark"
  # 对应模型的url 参考 https://www.xfyun.cn/doc/spark/Web.html#_1-%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E
  base_url: "wss://spark-api.xf-yun.com/v4.0/chat" 
  app_id: "98ec2cbc"
  api_key: "aeda4169d81c8b53875b8edc247c3fc1"
  api_secret: "NGM3YzE2NDk2MjhhN2RiZjg4Y2U1ZDhi"
  domain: "4.0Ultra" # 取值为 [general,generalv2,generalv3,generalv3.5] 和url一一对应
